[theme]
base = "dark"
primaryColor = "#d6a250"
backgroundColor = "#0d0e10"
secondaryBackgroundColor = "#191b1f"
textColor = "#e8e6e1"
font = "sans serif"

[server]
headless = true
port = 8502
maxUploadSize = 2000

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
